### ISSUE TITLE
Demo doesn't seem to be working.

### ISSUE THREAD

**Issue by pviejo** [jawg/taxonomy#1]
Is this still an active repo? Doesn't seem to be updated in a long time and not working in demo.

**Comment by Joxit** [comment]
Hi, thank you for the issue.

I've updated the [demo](https://jawg.github.io/taxonomy/demo/), now it uses the basic example.

The taxonomy project do not support Mapbox GL expressions yet, that's why the demos was not working.

If you need new features, we can still improve the project and we also accept new PR.

**Comment by pviejo** [comment]
Thanks! Looks great. I have a project I would like to use taxonomies and this is a great help.

**Comment by Joxit** [comment]
I'm glad that you are using our project :smile: 

I added the support for `interpolate` expression in 6644c95231506a14132fccedd1897bf394ffe0ff

The next step will be `match` expression. IDK yet how this will work....

**Comment by Joxit** [comment]
I will close this issue. Feel free to open another if something is wrong.
